(function(){
"use strict";
const $=id=>document.getElementById(id);
const sb=window.supabase&&window.ZANSTI_SUPABASE&&window.ZANSTI_SUPABASE.ready?window.supabase.createClient(window.ZANSTI_SUPABASE.url,window.ZANSTI_SUPABASE.publishableKey):null;
const storeKey="avasin_standard_spelling_rules_v1";
let rules=[],pending=[],owner=false;
function message(s){let el=$("msg");if(el){el.textContent=s;el.style.display="block";}}
function save(){localStorage.setItem(storeKey,JSON.stringify(rules));}
function drawRules(){let root=$("rules");root.replaceChildren();rules.forEach((r,i)=>{let row=document.createElement("div");row.className="rule";let label=document.createElement("span");label.textContent=r.old+"  ←  "+r.new;let del=document.createElement("button");del.className="btn secondary";del.textContent="سڕینەوە";del.onclick=()=>{rules.splice(i,1);save();drawRules();};row.append(label,del);root.append(row);});if(!rules.length)root.textContent="هێشتا هیچ یاسایەک نییە."; }
function add(){let old=$("old").value,newText=$("new").value;if(!old.trim()||!newText.trim()||old===newText){message("وشەی کۆن و نوێ بە دروستی پڕ بکەرەوە.");return;}if(rules.some(r=>r.old===old)){message("ئەم یاسایە پێشتر هەیە.");return;}rules.push({old,new:newText});save();drawRules();$("old").value="";$("new").value="";}
function selectedScope(){return document.querySelector('input[name="scope"]:checked').value;}
function inScope(row){let s=selectedScope();return s==="all"||row.course_id===s;}
function protectedText(n){return n.parentElement&&n.parentElement.closest("script,style,code,pre,blockquote,[data-source],.source-card,.lesson-source,.source-reference,figure");}
function transform(html,skip){let d=new DOMParser().parseFromString("<div id='root'>"+html+"</div>","text/html"),root=d.getElementById("root"),w=d.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[],count=0;while(w.nextNode())nodes.push(w.currentNode);for(let n of nodes){if(skip&&protectedText(n))continue;let t=n.nodeValue;for(let r of rules){let at=0;while((at=t.indexOf(r.old,at))!==-1){t=t.slice(0,at)+r.new+t.slice(at+r.old.length);count++;at+=r.new.length;}}n.nodeValue=t;}return {html:root.innerHTML,count};}
async function preview(){if(!rules.length){message("سەرەتا یاسایەک زیاد بکە.");return;}if(!sb){message("پەیوەندی بنکەدراوە ئامادە نییە.");return;}let b=$("preview");b.disabled=true;pending=[];try{let {data,error}=await sb.from("lesson_content").select("lesson_key,course_id,title,content_html").order("lesson_key");if(error)throw error;for(let row of (data||[]).filter(inScope)){let result=transform(row.content_html,$("skip").checked);if(result.html!==row.content_html)pending.push({...row,next:result.html,count:result.count});}let root=$("previewList");root.replaceChildren();let total=0;for(let row of pending){total+=row.count;let card=document.createElement("div");card.className="item";card.textContent=row.lesson_key+" — "+row.title+" · "+row.count+" گۆڕان";root.append(card);}message("پشکنین تەواو بوو: "+(data||[]).filter(inScope).length+" وانە پشکنرا؛ "+pending.length+" وانە گۆڕانکارییان تێدایە؛ "+total+" گۆڕینی دەقی دۆزرایەوە. تا ئێستا هیچ شتێک پاشەکەوت نەکراوە.");$("apply").disabled=!pending.length;}catch(e){message("هەڵە لە پشکنین: "+e.message);}finally{b.disabled=false;}}
async function apply(){if(!owner){message("تەنیا خاوەنماڵپەڕ دەتوانێت جێبەجێ بکات.");return;}if(!pending.length)return;if(!confirm("دڵنیایت لە جێبەجێکردنی گۆڕانکارییە پێش‌نمایشکراوەکان؟"))return;let ok=0,errors=[];let b=$("apply");b.disabled=true;for(let row of pending){let {data,error}=await sb.from("lesson_content").update({content_html:row.next,updated_at:new Date().toISOString()}).eq("lesson_key",row.lesson_key).select("lesson_key");if(error||!data||!data.length)errors.push(row.lesson_key+": "+(error?error.message:"گۆڕانکاری پاشەکەوت نەکرا"));else ok++;}message("تەواو: "+ok+" وانە نوێ کرایەوە؛ "+errors.length+" هەڵە."+ (errors.length?"\n"+errors.join("\n"):""));if(!errors.length){pending=[];$("previewList").replaceChildren();$("apply").disabled=true;}else b.disabled=false;}
$("add").onclick=add;$("preview").onclick=preview;$("apply").onclick=apply;
$("export").onclick=()=>{let a=document.createElement("a"),blob=new Blob([JSON.stringify(rules,null,2)],{type:"application/json"});a.href=URL.createObjectURL(blob);a.download="avasin-spelling-rules.json";a.click();URL.revokeObjectURL(a.href);};
$("import").onclick=()=>$("file").click();$("file").onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data)||data.some(r=>!r||typeof r.old!=="string"||typeof r.new!=="string"||!r.old||r.old===r.new))throw Error("فۆرماتی یاساکان دروست نییە");rules=data;save();drawRules();message("یاساکان هاوردە کران.");}catch(err){message("هەڵە: "+err.message);}e.target.value="";};
$("logout").onclick=async()=>{if(sb)await sb.auth.signOut();location.href="auth.html";};
try{rules=JSON.parse(localStorage.getItem(storeKey)||"[]");if(!Array.isArray(rules))rules=[];}catch(e){rules=[];}drawRules();
(async()=>{if(!sb){message("Supabase ئامادە نییە.");return;}let {data:{session}}=await sb.auth.getSession();if(!session){location.replace("auth.html?next=spelling-tool.html");return;}let {data,error}=await sb.rpc("is_site_owner");if(error||data!==true){document.querySelector("main").textContent="ئەم ئامرازە تەنیا بۆ خاوەنماڵپەڕە.";return;}owner=true;})();
})();